"""Emotion 包（Life Simulation P2）：确定性情感引擎（不用 LLM）。"""
from .engine import (
    EmotionEngine, EmotionDelta, EVENT_DELTAS, DIMENSIONS,
    EVENT_PET, EVENT_POKE, EVENT_CLICK, EVENT_DRAG, EVENT_FEED, EVENT_PRAISE,
    EVENT_IGNORE, EVENT_REJECT, EVENT_TALK, EVENT_WORK_START, EVENT_WORK_END,
    EVENT_RETURN, EVENT_AGENT_DONE, EVENT_FOOD,
)

__all__ = [
    "EmotionEngine", "EmotionDelta", "EVENT_DELTAS", "DIMENSIONS",
    "EVENT_PET", "EVENT_POKE", "EVENT_CLICK", "EVENT_DRAG", "EVENT_FEED",
    "EVENT_PRAISE", "EVENT_IGNORE", "EVENT_REJECT", "EVENT_TALK",
    "EVENT_WORK_START", "EVENT_WORK_END", "EVENT_RETURN", "EVENT_AGENT_DONE", "EVENT_FOOD",
]
